### ISSUE TITLE
Add a Red Eclipse theme to the interface.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/statsdb-interface#6]
The interface should have a Red Eclipse theme to fit with the main page and game, this theme could be taken directly from http://redeclipse.net/

**Comment by TheAssassin** [comment]
I agree that it should look more like Red Eclipse and its homepage. Such a Bootstrap 3 theme would also be useful for my project (https://github.com/TheAssassin/redflare-python).
The problem is that the theme that can be found on http://redeclipse.net lacks some style changes e.g. for tables which are heavily used in this project, and it also contains some elements that are not necessary or are very specific.

Maybe we should think about creating a proper Bootstrap 3 theme (i.e. as a separate project). The amount of work is probably even lower than the common way of adjusting single elements using standard CSS, and the resulting patches contain less lines of code than creating an overlay in standard CSS (like it was done for http://redeclipse.net). As soon as it is finished, it could be used on http://redeclipse.net, too.

**Comment by TheAssassin** [comment]
I deployed a version of the mentioned Bootswatch theme on the running instance. Currently awaits feedback.

**Comment by shacknetisp** [comment]
https://github.com/red-eclipse/bootswatch
